name: Build Multiple Platforms

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      # Cache
      - uses: actions/cache@v3
        with:
          path: BossRushGame/Library
          key: Library-${{ hashFiles('BossRushGame/Assets/**', 'BossRushGame/Packages/**', 'BossRushGame/ProjectSettings/**') }}-${{ matrix.targetPlatform }}
          restore-keys: |
                Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: BossRushGame
          buildName: BossRushGame

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Download WebGL build
        uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          path: builds/webgl/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Deploy WebGL build to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: builds/webgl # The folder the action should deploy.
        
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: builds/win/
      - run: pwd
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/**
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

