name: Build WebGL

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      # Cache
      - uses: actions/cache@v3
        with:
          path: BossRushGame/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
                Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: BossRushGame

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  # Single deploy job since we're just deploying
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        # with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          # name: Build # optional
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          # path: # optional
          # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          # pattern: # optional
          # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
          # merge-multiple: # optional, default is false
          # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          # github-token: # optional
          # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
          # repository: # optional, default is ${{ github.repository }}
          # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
          # run-id: # optional, default is ${{ github.run_id }}
                
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: $GITHUB_WORKSPACE
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

